# Generated by Django 5.1.15 on 2026-06-08 06:08

import django.db.models.deletion
import inspections.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ml', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pipeline_code', models.SlugField(max_length=80)),
                ('pipeline_version', models.CharField(max_length=120)),
                ('source', models.CharField(choices=[('mobile', 'Mobile'), ('server', 'Server'), ('manual', 'Manual')], default='mobile', max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=32)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('summary_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['inspection', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_code', models.SlugField(max_length=80)),
                ('stage_name', models.CharField(blank=True, max_length=255)),
                ('stage_order', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=32)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('result_json', models.JSONField(blank=True, default=dict)),
                ('latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='inspections.analysisrun')),
                ('model_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='analysis_stages', to='ml.mlmodelversion')),
            ],
            options={
                'ordering': ['analysis_run', 'stage_order', 'id'],
                'unique_together': {('analysis_run', 'stage_code', 'stage_order')},
            },
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captured_at', models.DateTimeField()),
                ('uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('original_image', models.ImageField(upload_to=inspections.models.inspection_upload_path)),
                ('annotated_image', models.ImageField(blank=True, upload_to=inspections.models.inspection_upload_path)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('location_accuracy_m', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('analyzed', 'Analyzed'), ('queued', 'Queued'), ('uploaded', 'Uploaded'), ('invalid_photo', 'Invalid photo'), ('no_weld_detected', 'No weld detected'), ('needs_review', 'Needs review'), ('reviewed', 'Reviewed')], default='draft', max_length=32)),
                ('summary_json', models.JSONField(blank=True, default=dict)),
                ('worker_snapshot_json', models.JSONField(blank=True, default=dict)),
                ('app_version', models.CharField(blank=True, max_length=64)),
                ('device_id', models.CharField(blank=True, max_length=128)),
                ('device_info_json', models.JSONField(blank=True, default=dict)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inspections', to='organizations.area')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspections', to='organizations.organization')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inspections', to='organizations.site')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-captured_at'],
            },
        ),
        migrations.AddField(
            model_name='analysisrun',
            name='inspection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_runs', to='inspections.inspection'),
        ),
        migrations.CreateModel(
            name='Detection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.IntegerField()),
                ('class_name', models.CharField(max_length=120)),
                ('confidence', models.FloatField()),
                ('bbox_json', models.JSONField(blank=True, default=list)),
                ('mask_json', models.JSONField(blank=True, default=dict)),
                ('area_px', models.PositiveIntegerField(blank=True, null=True)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis_stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detections', to='inspections.analysisstage')),
            ],
            options={
                'ordering': ['analysis_stage', '-confidence'],
                'indexes': [models.Index(fields=['class_name', '-confidence'], name='inspections_class_n_1ac9af_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='inspection',
            index=models.Index(fields=['organization', '-captured_at'], name='inspections_organiz_08130c_idx'),
        ),
        migrations.AddIndex(
            model_name='inspection',
            index=models.Index(fields=['worker', '-captured_at'], name='inspections_worker__58549d_idx'),
        ),
        migrations.AddIndex(
            model_name='inspection',
            index=models.Index(fields=['status', '-captured_at'], name='inspections_status_517892_idx'),
        ),
        migrations.AddIndex(
            model_name='analysisrun',
            index=models.Index(fields=['pipeline_code', 'pipeline_version'], name='inspections_pipelin_e951a4_idx'),
        ),
    ]
