# Generated by Django 5.1.15 on 2026-06-08 07:03

import django.db.models.deletion
import inspections.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0001_initial'),
        ('ml', '0002_alter_mlmodel_options_alter_mlmodelversion_options_and_more'),
        ('organizations', '0002_alter_area_options_alter_organization_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analysisrun',
            options={'ordering': ['inspection', '-created_at'], 'verbose_name': 'запуск анализа', 'verbose_name_plural': 'запуски анализа'},
        ),
        migrations.AlterModelOptions(
            name='analysisstage',
            options={'ordering': ['analysis_run', 'stage_order', 'id'], 'verbose_name': 'этап анализа', 'verbose_name_plural': 'этапы анализа'},
        ),
        migrations.AlterModelOptions(
            name='detection',
            options={'ordering': ['analysis_stage', '-confidence'], 'verbose_name': 'обнаружение', 'verbose_name_plural': 'обнаружения'},
        ),
        migrations.AlterModelOptions(
            name='inspection',
            options={'ordering': ['-captured_at'], 'verbose_name': 'проверка', 'verbose_name_plural': 'проверки'},
        ),
        migrations.AlterField(
            model_name='analysisrun',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='создано'),
        ),
        migrations.AlterField(
            model_name='analysisrun',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='завершено'),
        ),
        migrations.AlterField(
            model_name='analysisrun',
            name='inspection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_runs', to='inspections.inspection', verbose_name='проверка'),
        ),
        migrations.AlterField(
            model_name='analysisrun',
            name='latency_ms',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='время выполнения, мс'),
        ),
        migrations.AlterField(
            model_name='analysisrun',
            name='pipeline_code',
            field=models.SlugField(max_length=80, verbose_name='код pipeline'),
        ),
        migrations.AlterField(
            model_name='analysisrun',
            name='pipeline_version',
            field=models.CharField(max_length=120, verbose_name='версия pipeline'),
        ),
        migrations.AlterField(
            model_name='analysisrun',
            name='source',
            field=models.CharField(choices=[('mobile', 'Телефон'), ('server', 'Сервер'), ('manual', 'Вручную')], default='mobile', max_length=32, verbose_name='источник'),
        ),
        migrations.AlterField(
            model_name='analysisrun',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='начато'),
        ),
        migrations.AlterField(
            model_name='analysisrun',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('running', 'Выполняется'), ('success', 'Успешно'), ('failed', 'Ошибка'), ('skipped', 'Пропущено')], default='pending', max_length=32, verbose_name='статус'),
        ),
        migrations.AlterField(
            model_name='analysisrun',
            name='summary_json',
            field=models.JSONField(blank=True, default=dict, verbose_name='сводка'),
        ),
        migrations.AlterField(
            model_name='analysisstage',
            name='analysis_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='inspections.analysisrun', verbose_name='запуск анализа'),
        ),
        migrations.AlterField(
            model_name='analysisstage',
            name='confidence',
            field=models.FloatField(blank=True, null=True, verbose_name='уверенность'),
        ),
        migrations.AlterField(
            model_name='analysisstage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='создано'),
        ),
        migrations.AlterField(
            model_name='analysisstage',
            name='latency_ms',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='время выполнения, мс'),
        ),
        migrations.AlterField(
            model_name='analysisstage',
            name='model_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='analysis_stages', to='ml.mlmodelversion', verbose_name='версия модели'),
        ),
        migrations.AlterField(
            model_name='analysisstage',
            name='result_json',
            field=models.JSONField(blank=True, default=dict, verbose_name='результат'),
        ),
        migrations.AlterField(
            model_name='analysisstage',
            name='stage_code',
            field=models.SlugField(max_length=80, verbose_name='код этапа'),
        ),
        migrations.AlterField(
            model_name='analysisstage',
            name='stage_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='название этапа'),
        ),
        migrations.AlterField(
            model_name='analysisstage',
            name='stage_order',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='порядок'),
        ),
        migrations.AlterField(
            model_name='analysisstage',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('running', 'Выполняется'), ('success', 'Успешно'), ('failed', 'Ошибка'), ('skipped', 'Пропущено')], default='pending', max_length=32, verbose_name='статус'),
        ),
        migrations.AlterField(
            model_name='detection',
            name='analysis_stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detections', to='inspections.analysisstage', verbose_name='этап анализа'),
        ),
        migrations.AlterField(
            model_name='detection',
            name='area_px',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='площадь, px'),
        ),
        migrations.AlterField(
            model_name='detection',
            name='bbox_json',
            field=models.JSONField(blank=True, default=list, verbose_name='рамка bbox'),
        ),
        migrations.AlterField(
            model_name='detection',
            name='class_id',
            field=models.IntegerField(verbose_name='ID класса'),
        ),
        migrations.AlterField(
            model_name='detection',
            name='class_name',
            field=models.CharField(max_length=120, verbose_name='класс'),
        ),
        migrations.AlterField(
            model_name='detection',
            name='confidence',
            field=models.FloatField(verbose_name='уверенность'),
        ),
        migrations.AlterField(
            model_name='detection',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='создано'),
        ),
        migrations.AlterField(
            model_name='detection',
            name='mask_json',
            field=models.JSONField(blank=True, default=dict, verbose_name='маска'),
        ),
        migrations.AlterField(
            model_name='detection',
            name='metadata_json',
            field=models.JSONField(blank=True, default=dict, verbose_name='метаданные'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='annotated_image',
            field=models.ImageField(blank=True, upload_to=inspections.models.inspection_upload_path, verbose_name='фото с анализом'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='app_version',
            field=models.CharField(blank=True, max_length=64, verbose_name='версия приложения'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inspections', to='organizations.area', verbose_name='участок'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='captured_at',
            field=models.DateTimeField(verbose_name='время съемки'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='comment',
            field=models.TextField(blank=True, verbose_name='комментарий'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='создано'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='device_id',
            field=models.CharField(blank=True, max_length=128, verbose_name='ID устройства'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='device_info_json',
            field=models.JSONField(blank=True, default=dict, verbose_name='данные устройства'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='широта'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='location_accuracy_m',
            field=models.FloatField(blank=True, null=True, verbose_name='точность геолокации, м'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='долгота'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspections', to='organizations.organization', verbose_name='предприятие'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='original_image',
            field=models.ImageField(upload_to=inspections.models.inspection_upload_path, verbose_name='исходное фото'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inspections', to='organizations.site', verbose_name='объект'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('analyzed', 'Проанализировано'), ('queued', 'В очереди'), ('uploaded', 'Загружено'), ('invalid_photo', 'Некорректное фото'), ('no_weld_detected', 'Шов не обнаружен'), ('needs_review', 'Требует проверки'), ('reviewed', 'Проверено')], default='draft', max_length=32, verbose_name='статус'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='summary_json',
            field=models.JSONField(blank=True, default=dict, verbose_name='сводка анализа'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='обновлено'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='uploaded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='время загрузки'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspections', to=settings.AUTH_USER_MODEL, verbose_name='работник'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='worker_snapshot_json',
            field=models.JSONField(blank=True, default=dict, verbose_name='снимок данных работника'),
        ),
    ]
