# Generated by Django 5.1.15 on 2026-06-08 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'ordering': ['site__organization__name', 'site__name', 'name'], 'verbose_name': 'участок', 'verbose_name_plural': 'участки'},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ['name'], 'verbose_name': 'предприятие', 'verbose_name_plural': 'предприятия'},
        ),
        migrations.AlterModelOptions(
            name='site',
            options={'ordering': ['organization__name', 'name'], 'verbose_name': 'объект', 'verbose_name_plural': 'объекты'},
        ),
        migrations.AlterField(
            model_name='area',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='создано'),
        ),
        migrations.AlterField(
            model_name='area',
            name='description',
            field=models.TextField(blank=True, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='area',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='активно'),
        ),
        migrations.AlterField(
            model_name='area',
            name='name',
            field=models.CharField(max_length=255, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='area',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='areas', to='organizations.site', verbose_name='объект'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='создано'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='inn',
            field=models.CharField(blank=True, max_length=32, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='активно'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='short_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='краткое название'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='обновлено'),
        ),
        migrations.AlterField(
            model_name='site',
            name='address',
            field=models.TextField(blank=True, verbose_name='адрес'),
        ),
        migrations.AlterField(
            model_name='site',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='создано'),
        ),
        migrations.AlterField(
            model_name='site',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='активно'),
        ),
        migrations.AlterField(
            model_name='site',
            name='name',
            field=models.CharField(max_length=255, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='site',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sites', to='organizations.organization', verbose_name='предприятие'),
        ),
    ]
