# Generated by Django 5.1.15 on 2026-06-08 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MlModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('task_type', models.CharField(choices=[('classification', 'Classification'), ('detection', 'Detection'), ('segmentation', 'Segmentation'), ('pipeline', 'Pipeline'), ('other', 'Other')], max_length=32)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='MlModelVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=120)),
                ('format', models.CharField(blank=True, max_length=32)),
                ('file_hash', models.CharField(blank=True, max_length=128)),
                ('input_size', models.CharField(blank=True, max_length=64)),
                ('classes_json', models.JSONField(blank=True, default=dict)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='ml.mlmodel')),
            ],
            options={
                'ordering': ['model__code', '-created_at'],
                'unique_together': {('model', 'version')},
            },
        ),
    ]
