# Generated by Django 5.1.15 on 2026-06-08 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mlmodel',
            options={'ordering': ['code'], 'verbose_name': 'ML-модель', 'verbose_name_plural': 'ML-модели'},
        ),
        migrations.AlterModelOptions(
            name='mlmodelversion',
            options={'ordering': ['model__code', '-created_at'], 'verbose_name': 'версия ML-модели', 'verbose_name_plural': 'версии ML-моделей'},
        ),
        migrations.AlterField(
            model_name='mlmodel',
            name='code',
            field=models.SlugField(max_length=80, unique=True, verbose_name='код'),
        ),
        migrations.AlterField(
            model_name='mlmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='создано'),
        ),
        migrations.AlterField(
            model_name='mlmodel',
            name='description',
            field=models.TextField(blank=True, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='mlmodel',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='активно'),
        ),
        migrations.AlterField(
            model_name='mlmodel',
            name='name',
            field=models.CharField(max_length=255, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='mlmodel',
            name='task_type',
            field=models.CharField(choices=[('classification', 'Классификация'), ('detection', 'Детекция'), ('segmentation', 'Сегментация'), ('pipeline', 'Pipeline'), ('other', 'Другое')], max_length=32, verbose_name='тип задачи'),
        ),
        migrations.AlterField(
            model_name='mlmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='обновлено'),
        ),
        migrations.AlterField(
            model_name='mlmodelversion',
            name='classes_json',
            field=models.JSONField(blank=True, default=dict, verbose_name='классы'),
        ),
        migrations.AlterField(
            model_name='mlmodelversion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='создано'),
        ),
        migrations.AlterField(
            model_name='mlmodelversion',
            name='file_hash',
            field=models.CharField(blank=True, max_length=128, verbose_name='hash файла'),
        ),
        migrations.AlterField(
            model_name='mlmodelversion',
            name='format',
            field=models.CharField(blank=True, max_length=32, verbose_name='формат'),
        ),
        migrations.AlterField(
            model_name='mlmodelversion',
            name='input_size',
            field=models.CharField(blank=True, max_length=64, verbose_name='размер входа'),
        ),
        migrations.AlterField(
            model_name='mlmodelversion',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='активно'),
        ),
        migrations.AlterField(
            model_name='mlmodelversion',
            name='metadata_json',
            field=models.JSONField(blank=True, default=dict, verbose_name='метаданные'),
        ),
        migrations.AlterField(
            model_name='mlmodelversion',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='ml.mlmodel', verbose_name='модель'),
        ),
        migrations.AlterField(
            model_name='mlmodelversion',
            name='version',
            field=models.CharField(max_length=120, verbose_name='версия'),
        ),
    ]
